
--COMPANIES FROM CSV in h2
INSERT INTO users(ID, CREATED_AT, DELETED, UPDATED_AT, EMAIL) SELECT ID, CURRENT_TIMESTAMP, FALSE, CURRENT_TIMESTAMP, EMAIL from CSVREAD('src\\main\\resources\\companies.csv', NULL );
INSERT INTO COMPANIES( ID, SHORT_NAME, NAME, COMPANY_TYPE, ADDRESS, FK_ADVISER_ID,FK_SEMESTER_ID) SELECT ID,SHORT_NAME,NAME,COMPANY_TYPE,ADDRESS,FK_ADVISER_ID,FK_SEMESTER_ID FROM CSVREAD( 'src\\main\\resources\\companies.csv', NULL );
